### ISSUE TITLE
TooManyRequestsException: Rate exceeded

### ISSUE THREAD

**Issue by Zophar78** [mifi/cognito-backup#12]
I have a strange issue... I've packaged backup-cognito on a docker image. When executing it from my local machine on a 5000 user pools it works 100% of time. But when i execute it on the jenkins node i have on AWS i get a TooManyRequestsException. I tried to change the value of the limiter... nothing change... any clue? How can i get more debug, messages on it?

```
/usr/local/bin/cognito-backup backup-users eu-west-1_eTHaDFrjR --region eu-west-1
TooManyRequestsException: Rate exceeded
    at Request.extractError (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cognito-backup/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by mifi** [comment]
Hi. The limiter is only for restore, not for backup, so it shouldn't change anything.
Maybe there are too many requests on a given time, you could try with a setTimeout() between the page calls

**Comment by Zophar78** [comment]
Hello @mifi,
Thanks for the answer. What do you mean exactly by "try with a setTimeout() between the page calls"... any direction, lines of code i should look for?

**Comment by mifi** [comment]
oops forgot about this one. are you still experiencing this issue? any sure way to reproduce it?

**Comment by Zophar78** [comment]
No all good on my side. Never reproduce it again. Thanks we can close it.
